package:
  name: aws-network-policy-agent
  version: "1.2.0"
  epoch: 100
  description: Amazon EKS Network Policy Agent is a daemonset that is responsible for enforcing configured network policies on the cluster.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - clang-16-dev
      - libbpf-dev
      - llvm16-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/aws/aws-network-policy-agent
      tag: v${{package.version}}
      # WARNING Also please upgrade vmlinux.h header by hand using generate-vmlinuxh.sh
      # TODO:
      # Note that script relies on launchad AL2023 docker container to
      # get AL2023 kernel image. Maybe we should package dnf tooling
      # in wolfi, to be able to download AL2023 kernel as a build
      # dependency at build-time instead
      expected-commit: 8f91f60083828e096cccc0cec8de30c3aeeb248c

  - uses: go/build
    with:
      tags: netgo,ebpf,core
      output: controller
      packages: main.g

  - uses: go/build
    with:
      output: aws-eks-na-cli
      packages: ./cmd/cli

  - uses: go/build
    with:
      output: aws-eks-na-cli-v6
      packages: ./cmd/cliv6

  - uses: strip

update:
  enabled: true
  github:
    identifier: aws/aws-network-policy-agent
    strip-prefix: v
