package:
  name: fluent-operator-3.2.0-r4
  version: 3.2.0
  epoch: 100
  description: Operate Fluent Bit and Fluentd in the Kubernetes way - Previously known as FluentBit Operator
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - go

var-transforms:
  - from: ${{package.version}}
    match: ^(\d)\.(\d)\.(\d)$
    replace: $1
    to: fluent-major-version
  - from: ${{package.version}}
    match: ^(\d)\.(\d)\.(\d)$
    replace: $2
    to: fluent-minor-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/fluent/fluent-operator
      expected-commit: aabb8198c080f55f3e1e575ef8951c5900cb2a6a
      tag: v${{package.version}}

  - uses: go/build
    with:
      output: manager
      packages: ./cmd/fluent-manager/main.go

subpackages:
  - name: fluent-watcher
    pipeline:
      - uses: go/build
        with:
          packages: ./cmd/fluent-watcher/fluentbit
          output: fluent-watcher

  - name: fluent-watcher-config
    dependencies:
      replaces:
        # A "replaces" must match the package origin's full name. Since we use
        # a version stream for fluent-bit, we must append fluent-bit-3.1
        # exactly.
        #
        # Our automation has no way of linking fluent-operator to
        # fluent-bit updates, so to ensure this doesn't silently fail when
        # fluent-bit rolls forward, we have a test stanza below that ensures
        # fluent-operator can always be installed alongside fluent-bit.
        #
        # When this test fails, that likely means fluent-bit rolled forward to
        # a new version stream anad must be updated in the "replaces" block
        # below
        - fluent-bit-${{vars.fluent-major-version}}.${{vars.fluent-minor-version}}
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/fluent-bit/etc
          cp conf/fluent-bit.conf conf/fluent-bit.yaml conf/parsers.conf \
            conf/fluent-bit.conf "${{targets.contextdir}}"/fluent-bit/etc

  - name: fluent-watcher-compat
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/fluent-bit/bin/
          ln -s /usr/bin/fluent-watcher "${{targets.contextdir}}"/fluent-bit/bin/fluent-watcher

update:
  enabled: true
  github:
    identifier: fluent/fluent-operator
    strip-prefix: v
    use-tag: true
