package:
  name: grafana-image-renderer
  version: 3.11.6
  epoch: 100
  description: A Grafana backend plugin that handles rendering of panels & dashboards to PNGs using headless browser (Chromium/Chrome)
  copyright:
    - license: Apache-2.0
  target-architecture:
    - x86_64
  dependencies:
    runtime:
      - busybox
      - chromium
      - dumb-init
      - nodejs

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - nodejs
      - scanelf
      - ttf-dejavu
      - yarn

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/grafana/grafana-image-renderer
      tag: v${{package.version}}
      expected-commit: 61d808662b646f9fd1ec322ada2cb7acc20f706a

  - runs: |
      yarn install
      yarn build

      # Node module installs multi-arch libraries, this deletes them
      scanelf -R -n . | awk '/aarch64/ {print $NF}' | xargs rm -rf

      mkdir -p ${{targets.destdir}}/usr/src/app/

      cp -r ./proto ${{targets.destdir}}/usr/src/app/
      cp -r ./build ${{targets.destdir}}/usr/src/app/
      cp -r ./node_modules ${{targets.destdir}}/usr/src/app/
      cp ./default.json ${{targets.destdir}}/usr/src/app/config.json
      cp ./plugin.json ${{targets.destdir}}/usr/src/app/

update:
  enabled: true
  github:
    identifier: grafana/grafana-image-renderer
    strip-prefix: v
