package:
  name: karpenter-1.1
  version: 1.1.1
  epoch: 100
  description: Karpenter is a Kubernetes Node Autoscaler built for flexibility, performance, and simplicity.
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - karpenter=${{package.full-version}}
      - karpenter-provider-aws=${{package.full-version}}

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/aws/karpenter-provider-aws
      tag: v${{package.version}}
      expected-commit: 3298d9152423198feef64bb1d02036ac6fdd65e5

  - uses: go/build
    with:
      packages: ./cmd/controller
      output: controller
      ldflags: -X=sigs.k8s.io/karpenter/pkg/operator.Version=${{package.version}}

update:
  enabled: true
  github:
    identifier: aws/karpenter-provider-aws
    tag-filter: v1.1.
    strip-prefix: v
