package:
  name: reflex-0.6.6-r0
  version: 0.6.6
  epoch: 101 # GHSA-59g5-xgcq-4qw3
  description: Web apps in pure Python
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - bash
      - curl
      - python-3
      - wget

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - openssf-compiler-options
      - poetry
      - py3-pip
      - py3-setuptools
      - python3
      - python3-dev
      - wolfi-base
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/reflex-dev/reflex
      tag: v${{package.version}}
      expected-commit: 0c8192222fe8a6258e768fef82336dce3566671f

  - uses: patch
    with:
      patches: GHSA-59g5-xgcq-4qw3.patch

  - runs: '#Fix CVEs

      poetry add "idna==3.7"


      poetry run pip freeze | grep -v reflex > requirements.txt

      poetry build


      pip install --root ${{targets.destdir}} -I -r requirements.txt --no-compile

      pip install --root ${{targets.destdir}} dist/reflex-*.whl

      find ${{targets.destdir}}/usr/lib/python*/site-packages/ \( -type d -a -name test -o -name tests \) -o \( -type f -a -name ''*.pyc'' -o -name ''*.pyo'' \) -exec rm -rf ''{}'' \+

    '

update:
  ignore-regex-patterns:
    - post1
  enabled: true
  github:
    identifier: reflex-dev/reflex
    strip-prefix: v
