package:
  name: step-0.28.2-r4
  version: 0.28.2
  epoch: 100
  description: A zero trust swiss army knife for working with X509, OAuth, JWT, OATH OTP, etc.
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/smallstep/cli
      tag: v${{package.version}}
      expected-commit: 6fb3e24fe731b0ce5b82478cabf778d01d135ea7

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0 golang.org/x/net@v0.33.0

  - uses: go/build
    with:
      packages: ./cmd/step
      output: step
      ldflags: -X main.Version=${{package.version}}

update:
  enabled: true
  github:
    identifier: smallstep/cli
    strip-prefix: v
