package:
  name: ts-patch
  version: 3.2.1
  epoch: 101 # GHSA-952p-6rrq-rcjv
  description: "Patch typescript to allow custom transformers (plugins) during build"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - nodejs-16
      - npm
      - typescript

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - nodejs-16
      - npm
      - rsync

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/nonara/ts-patch.git
      tag: v${{package.version}}
      expected-commit: 41b2112495265819558e48f3d56a81dfb4533005

  - uses: patch
    with:
      patches: GHSA-952p-6rrq-rcjv.patch

  - name: npm install
    runs: |
      npm install && npm run build
      mkdir -p ${{targets.destdir}}/usr/lib/node_modules/ts-patch
      rsync -av --exclude='melange-out' /home/build/* ${{targets.destdir}}/usr/lib/node_modules/ts-patch

      mkdir -p ${{targets.destdir}}/usr/bin/
      ln -sf /usr/lib/node_modules/ts-patch/node_modules/ts-patch/bin/tspc.js ${{targets.destdir}}/usr/bin/tspc
      ln -sf /usr/lib/node_modules/ts-patch/node_modules/ts-patch/bin/ts-patch.js ${{targets.destdir}}/usr/bin/ts-patch

update:
  enabled: true
  github:
    identifier: nonara/ts-patch
    strip-prefix: v
