name: Run pombump tool to update versions and properties in a Maven POM file
needs:
  packages:
    - busybox
    - pombump

inputs:
  patch-file:
    description: |
      Patches file to use for updating the POM file
    default: ./pombump-deps.yaml
  properties-file:
    description: |
      Properties file to be used for updating the POM file
    default: ./pombump-properties.yaml
  dependencies:
    description: |
      Dependencies to be used for updating the POM file via command line flag
  properties:
    description: |
      Properties to update / add the POM file via command line flag
  pom:
    description: |
      Path to pom.xml
    default: pom.xml
  debug:
    description: |
      Enable debug mode, which will print out the diffs of the pom.xml file after running pombump
    default: false


pipeline:
  - runs: |
      PATCH_FILE_FLAG=""
      PROPERTIES_FILE_FLAG=""
      DEPENDENCIES_FLAG=""
      PROPERTIES_FLAG=""

      if [ -n "${{inputs.dependencies}}" ]; then
        DEPENDENCIES_FLAG="--dependencies ${{inputs.dependencies}}"
      elif [ -f "${{inputs.patch-file}}" ]; then
        PATCH_FILE_FLAG="--patch-file ${{inputs.patch-file}}"
      fi

      if [ -f "${{inputs.properties-file}}" ]; then
        PROPERTIES_FILE_FLAG="--properties-file ${{inputs.properties-file}}"
      fi

      if [ -n "${{inputs.properties}}" ]; then
        PROPERTIES_FLAG="--properties ${{inputs.properties}}"
      fi

      pombump ${{inputs.pom}} $PATCH_FILE_FLAG $PROPERTIES_FILE_FLAG $DEPENDENCIES_FLAG $PROPERTIES_FLAG > "${{inputs.pom}}.new"

      if [ "${{inputs.debug}}" = "true" ]; then
        # If there are any differences, it will return a non-zero exit code, so we use `|| true` to ignore that
        diff -w "${{inputs.pom}}" "${{inputs.pom}}.new" || true
      fi

      mv "${{inputs.pom}}.new" ${{inputs.pom}}