issuer: https://accounts.google.com

# staging-enforce: ci-cve-scan-db889txsix2w7kfmlo@staging-enforce-cd1e.iam.gserviceaccount.com
subject_pattern: "(106173139749762516609)"

permissions:
  checks: write
