issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-dev/test-remediation-packages:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: chainguard-dev/test-remediation-packages/.github/workflows/delete-old-branches.yaml@refs/heads/main

permissions:
  contents: write
  pull_requests: read
