issuer: https://accounts.google.com

# TODO staging:
#  presubmit: ebuild-5wvot0p5tdbxthxsmo6inwk@staging-enforce-cd1e.iam.gserviceaccount.com
#  postsubmit: ebuild-7dl5wj4mopdicr283bey72j@staging-enforce-cd1e.iam.gserviceaccount.com
subject_pattern: "(105587019147205988443|110897445954037084144)"

permissions:
  contents: read
  checks: write
