issuer: https://accounts.google.com

# Have more than one service account
# - cve-detection-sa@staging-enforce-cd1e.iam.gserviceaccount.com 101982940773329773733
# - cve-detection-sa@prod-enforce-fabc.iam.gserviceaccount.com    111526393106232200098
subject_pattern: "(101982940773329773733|111526393106232200098)"

# Allow CVE detection automation to use Melange package information.
permissions:
  contents: read
