issuer: https://accounts.google.com

# Staging service account
# - cve-detection-sa@staging-enforce-cd1e.iam.gserviceaccount.com 101982940773329773733
subject_pattern: "101982940773329773733"

# Allow CVE detection automation to use Melange package information.
permissions:
  contents: read
