issuer: https://accounts.google.com

# cve-patch-forge-u2rgji37hclon9@staging-enforce-cd1e.iam.gserviceaccount.com
# lc-cve-patch-forge-cron@hector-mono.iam.gserviceaccount.com
# lc-cve-patch-forge-cron@staging-enforce-cd1e.iam.gserviceaccount.com
subject_pattern: "(116008995223794447520|101488056342408075939|104031871496703805161)"

permissions:
  pull_requests: write
  contents: write
  workflows: write
