# Copyright 2025 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-dev/test-remediation-packages:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: chainguard-dev/test-remediation-packages/.github/workflows/stale.yaml@refs/heads/main

permissions:
  pull_requests: write
  contents: read
